---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    secure: "XfPWpXmGf8oSJweB5hiwqhF5FyMAv6j4lviJ834poJkKvYjktemnJpYSSWQroEOm6KmWJud/hjfcIWJLfqKtx45km5BuQMiLvFkBecrNdBZlbZ4ZW0bKylFCEF3Ee6nsSTr7To+dksRXgAAgWqfEhWHq3wyUY9W9vGzZbewM3lbV39+l5+Zkz5u5Q7ZH4+T7RqZV7RZ60AkQRNGIMCH4VQ+LTzj9T28siAA2axwLjwZU0WMFY/NQCh3iz34GanFKd4qWUPCp0YPqmp2fArlmoKgu4ggkFPxEBN36qhxpm76gYZWc3CX04DDEyxviEewNd8zfLeMzxzivbH1DgzVuPkwcTxh+zFKdfVEC4CsgjUVWpDBBLS4FQ+8hGINJJbuUC18+4cZA0ym2YOBWpKqwKUmr4wTiWxUCSHY8gaV+xskVCePm/l/0USJEQuZVfEsbzP7Lej1bVJlWzAA2mfP+eQw7VucaLooGIaQ7JcWYQei0oUn3HAKfOvSFXecO/2gIgZE7aTErSGeIj/5zwPR43Xbp1RJjuG4NGGp6JoPoDRGyw00zXHyZ1DLTSPWnldz2m1jR0CIBmdHZMcysaiuoe6b0Xndwp+XNiCrvQhp4fnM6YHrPeZrko7hC2+/Jm0hgNMdnMaINAGcv50TWbMOSiR1sEEdLZ8rBngoq6lEV7tg="
